title: Sys Admin Ninja
iconURL: assets/default-icon.png
theme: jekyll-theme-hacker

# for a clean URL
permalink: :slug

social:
  twitter: cueva_tux
  github: ##

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 4185
google_analytics: UA-28188202-1